/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvailableDate { 
    /**
     * Current date of a month title
     */
    date: string;
    /**
     * number of available units  use -1 for unknown
     */
    availableUnits: number;
}

