/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldForestCenter } from './fieldForestCenter';


/**
 * dfkdlfjkljdfk
 */
export interface FindFacilitiesDates { 
    fieldForestCenter?: FieldForestCenter;
    /**
     * First date range in reservation order
     */
    fromDate?: string;
    /**
     * sklskldskdlkdlsk
     */
    tillDate?: string;
}

