openapi: 3.0.1
info:
  description: Education new project|
  title: kkl Education API 
  version: 1.0.0
  contact:
    email: yochai@one1.co.il  
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/shivek/kkl-education/1.0.0
tags:
  - name: user
    description: Users functions
  - name: admin
    description: Admin functions only
paths: 
  '/lookup/FieldForestCenter':
    get:
      tags:
        - user
      operationId: getLookupFieldForestCenters
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:  
                  $ref: '#/components/schemas/FieldForestCenter'
  '/lookup/acommodationType':
    get:
      tags:
        - user
      operationId: getLookupAcommodationType  
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:  
                  $ref: '#/components/schemas/AcommodationType'              
  '/GetAvailableDates':
    post:
      tags:
        - user
      operationId: GetAvailableDates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchAvailableDatesOptions'  
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailableDate'  

  '/GetAvailableFacilities':
    post:
      tags:
        - user
      operationId: GetAvailableFacilities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FindFacilitiesDates'  
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FacilityDate'           
components:
  schemas:
    FieldForestCenter:
      type: object
      required: 
        - id
        - name
      properties:
        id:
          type: integer
          description: 'FieldForestCenter unique ID'
          title: "FieldForestCenter ID"
          example: 101
        name:
          type: string
          description: 'Field & Forest Center name'
          title: "FieldForestCenter Name"
          example: 'נס הרים'
        iconPath:
          type: string
          description: 'yochai will check for path or base64'
          title: "icon"
          example: 'href...'
        acommodationList:
          type: array
          description: 'list of available  accomoadation types'
          items:
             $ref: '#/components/schemas/AcommodationType'
        linkSite :
          type: string
          description: 'gg'
          example: 'http://'

    AcommodationType:
      type: object
      required: 
        - id
        - name
      properties:
        id:
          type: integer
          description: 'Accomodation Type Id'
          title: "Guest cabin"
          example: '20'
        name:
          type: string
          description: 'Accomodation type name'
          title: "Accomodation Name"
          example: 'בקתה'
        maxOccupancy:
          type: integer
          description: 'max occupancy (beds) per one lodging place'
          example: 40
        totalUnits:
          type: integer
          description: 'm'
          example: 40
        img:
          type: string
          description: 'For compatibility reasons '
          example: '..href'
        nameEng :
          type: string
          description: 'For compatibility reasons'
          example: 'something'
    AvailableDate:
      type: object
      required: 
        - date
      properties:
        date:
          type: string
          format: date
          description:  'Current date of a month title'
          title: "date"
          example: '22-10-2021'
        availableBedsTent:
          type: integer
          description: 'available lodging places in tents'
          example: 20
        availableBedsCabin:
          type: integer
          description: 'available beds in cabins'
          example: 10
        availableBedsCamping:
          type: integer
          description: 'available lodging places in  campaing'
          example: 10
        availableBedsRoom:
          type: integer
          description: 'available beds in rooms'
          example: 10
        # availableUnits:
        #   type: integer
        #   title: "available units"
        #   description: 'number of available units  use -1 for unknown'
        #   example: 3
        #   minimum: -1
    SearchAvailableDatesOptions:
      type: object
      properties:
        FieldForestCenter:
          $ref: '#/components/schemas/FieldForestCenter'    
        fromDate:
          type: string
          format: date
          description: 'First date range in reservation order'
          title: "from date"
          example: '24-10-2021'
        tillDate:
          type: string
          format: date
          description: 'sklskldskdlkdlsk'
          title: "from date"
          example: '26-10-2021'
        # acommodationType:
        #    $ref: '#/components/schemas/AcommodationType'
        # singleDay:
        #   type: boolean
        #   description: 'Only one day tour'
        #   example: false
        #   title: 'single day'
    
    FacilityDate:
      type: object
      description: 'ttrtre'
      properties:
        today:
          type: string
          format: date
        facilitiesList:
          type: array
          items:
           $ref: '#/components/schemas/AvailableFacility'
    AvailableFacility:
      type: object
      required: 
        - id
        - name
      properties:
        id:
          type: integer
          description: 'Field-Forest-Center Facility Id'
          title: 'Facility Type Id'
          example: 8
        name:
          type: string
          description: 'Facility name'
          example: 'כיתה גדולה'
        maxOccupancy:
          type: integer
          description: ''
          example: 4
        occupiedHours:
         type: array
         items: 
          $ref: "#/components/schemas/OccupiedHours"
    OccupiedHours:
      type: object
      required: 
        - fromHour
        - tillHour
      properties:
        fromHour:
          type: string
          format: date-time
          example: '09:00'
        tillHour:
          type: string
          format: date-time
          example: '10:00'
    FindFacilitiesDates:
      type: object
      description: 'dfkdlfjkljdfk'
      properties:
        fieldForestCenter:
          $ref: '#/components/schemas/FieldForestCenter'    
        fromDate:
          type: string
          format: date
          description: 'First date range in reservation order'
          title: "from date"
          example: '24-10-2021'
        tillDate:
          type: string
          format: date
          description: 'sklskldskdlkdlsk'
          title: "from date"
          example: '26-10-2021'