/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvailableAccomodationDate { 
    /**
     * Current date of a month title
     */
    date: string;
    /**
     * available lodging places in tents
     */
    availableBedsTent?: number;
    /**
     * available beds in cabins
     */
    availableBedsCabin?: number;
    /**
     * available lodging places in  campaing
     */
    availableBedsCamping?: number;
    /**
     * available beds in rooms
     */
    availableBedsRoom?: number;
}

