/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.10.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccomodationFreeSpaces } from './accomodationFreeSpaces';


export interface AvailableAccomodationDate { 
    /**
     * Current date of a month title
     */
    date: string;
    /**
     * List of accomoadation free beds.
     */
    freeSpace?: Array<AccomodationFreeSpaces>;
}

