/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.12.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BaseCustomer { 
    id: number;
    name: string;
    address?: string;
    settlementId?: number | null;
    lastName?: string;
    contactName?: string;
    contactMobile?: string;
    contactEmail?: string;
    typeCode?: number | null;
    /**
     * Is the customer defined as not need to pay
     */
    noPayment?: number | null;
}

