/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';
import { ActivityType } from './activityType';
import { Budget } from './budget';


export interface BudgetByParams { 
    tripStart?: string;
    attribute?: Attribute;
<<<<<<< HEAD
    activity?: ActivityType;
=======
    activitiy?: ActivityType;
>>>>>>> searchPage-yael
    budget?: Budget;
    userName?: string;
    userId?: string;
    tripId?: number | null;
}

