/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { City } from './city';


export interface Budget { 
    desc?: string | null;
    kklAmount?: number;
    customerAmount?: number;
    type?: number;
    isByCity?: number | null;
    listCity?: Array<City> | null;
    cityId?: number;
    incomeBudget?: number;
    execution?: number;
    balance?: number;
    maofBalanceFin?: number;
    isNeedCalculate?: number | null;
    budget?: number;
    incomeId?: number;
    incomeName?: string;
    expensesId?: number;
    expensesName?: string;
}

