/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Charuz { 
    activityId?: number;
    name?: string | null;
    sitePicture?: string;
    linkToDetails?: string;
    hourStart?: string | null;
    hourEnd?: string | null;
    description?: string | null;
    date?: string;
    placeId?: number;
    placeName?: string;
    openBy?: string | null;
    itemId?: number | null;
    status?: number | null;
    generateTime?: string | null;
    subItemId?: number | null;
}

