/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Customer { 
    customerId?: number;
    customerName?: string;
    typeId?: number;
    typeName?: string;
    identificationTypeId?: number | null;
    idCode?: number | null;
    provinceId?: number | null;
    countryId?: number | null;
    countryName?: string;
    regionId?: number | null;
    regionName?: string;
    cityIdHebName?: string;
    streetNameHeb?: string;
    zipId?: number | null;
    phone?: string;
    phoneWorks?: string;
    fax?: string;
    email?: string;
    contactName?: string;
    contactPhone?: string;
    contactMobile?: string;
    userName?: string;
    generateDate?: string;
    appId?: number | null;
    noPayment?: number | null;
    internalCustomer?: number | null;
}

