/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Customer { 
    customerId?: number;
    customerName?: string;
    typeId?: number;
    typeName?: string | null;
    identificationTypeId?: number | null;
    idCode?: number | null;
    provinceId?: number | null;
    countryId?: number | null;
    countryName?: string;
    regionId?: number | null;
    regionName?: string | null;
    cityIdHebName?: string | null;
    streetNameHeb?: string | null;
    zipId?: number | null;
    phone?: string | null;
    phoneWorks?: string | null;
    fax?: string | null;
    email?: string | null;
    contactName?: string | null;
    contactPhone?: string | null;
    contactMobile?: string | null;
    userName?: string | null;
    generateDate?: string | null;
    appId?: number | null;
    noPayment?: number | null;
    internalCustomer?: number | null;
}

