/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FacilityOrder { 
    tripId?: number;
    facilityId?: number;
    orderId?: number | null;
    /**
     * refers to indentity record on data base
     */
    orderItemIdentity?: number | null;
    facilityName?: string;
    startDate?: string;
    endDate?: string;
    startHour?: string;
    endHour?: string;
    openBy?: string;
}

