/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LodgingGISFacility { 
    /**
     * the id of current structure as defined in the GIS
     */
    structureId?: number;
    /**
     * the structure name
     */
    structureType?: string;
    /**
     * three possible values - בנים, בנות,מעורב
     */
    gender?: string;
    /**
     * Possible values - פנוי, תפוס, בניקיון, בשיפוץ
     */
    status?: string;
}

