/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LodgingDetailsPerDay } from './lodgingDetailsPerDay';
import { NightNumberOptions } from './nightNumberOptions';


export interface LodgingReservation { 
    nightsCount?: Array<NightNumberOptions>;
    lodgingDetailsList?: Array<LodgingDetailsPerDay>;
}

