/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Lodging { 
    uid?: number;
    /**
     * Have four types - Cabin, tent, camping, room
     */
    type?: string;
    school?: number;
    /**
     * Two possible values - בנים, בנות
     */
    gender?: string;
    /**
     * Possible values - פנוי, תפוס, בניקיון, בשיפוץ
     */
    vacancy?: string;
    date?: string;
}

