/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * decribes ... 
 */
export interface OccupiedHours { 
    fromHour: string;
    tillHour: string;
<<<<<<< HEAD:src/app/open-api/model/occupiedHours.ts
    totalTime?: number;
=======
>>>>>>> searchPage-yael:src/app/api/model/occupiedHours.ts
    customerName?: string;
}

