/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OccupancyValidation { 
    centerFieldId?: number;
    startDate?: string;
    endDate?: string;
    startHour?: string | null;
    endHour?: string | null;
    typeSleepId?: number | null;
    quantityItem?: number;
    tripId?: number;
    orderId?: number | null;
    itemOrderRecordId?: number | null;
    classCode?: number | null;
    ischeckCooking?: number | null;
}

