/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { OrderType } from './orderType';
import { Supplier } from './supplier';


export interface Order { 
    tripId?: number;
    orderId?: number;
    status?: Status;
    orderType?: OrderType;
    supplier?: Supplier;
    comment?: string;
    siteId?: number | null;
    sentToSupplier?: string | null;
    sentBy?: string | null;
    voucherNum?: number | null;
    cancelDate?: string | null;
    causeCancellation?: string | null;
    cancelBy?: string | null;
    paidToSupplier?: number | null;
    userName?: string | null;
    openDate?: string | null;
    finOrderType?: string | null;
    budgetItem?: number | null;
    confirmDate?: string | null;
    confirmBy?: string | null;
    confirmUserTz?: number | null;
    confirmByUser?: string | null;
    confirmCancelBy?: string | null;
    confirmCancelByUser?: string | null;
    confirmCancelDate?: string | null;
    confirmCancelUserTz?: number | null;
    supplierProcedureNum?: string | null;
}

