/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.12.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemsByTypeOrder } from './itemsByTypeOrder';


export interface OrderItemCommonDetails { 
    /**
     * the unique item id
     */
    itemId?: number;
    /**
     * refers to indentity record on order table in data base
     */
    itemOrderRecordId?: number;
    /**
     * refers to indentity record on order table in data base
     */
    orderId?: number;
    tempOrderIdentity?: number | null;
    orderItemDetails?: ItemsByTypeOrder;
    supplierId?: number;
    quantity?: number;
    itemCost?: number;
    billingSupplier?: number | null;
    billingCustomer?: number | null;
    peopleInTrip?: number | null;
    location?: string;
    startDate?: string;
    endDate?: string;
    startHour?: string;
    endHour?: string;
    comments?: string;
    internalComment?: string;
    openDate?: string;
    userInfo?: string;
}

