/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { OrderType } from './orderType';
import { Supplier } from './supplier';


export interface Order { 
    tripId?: number;
    orderId?: number;
    status?: Status;
    orderType?: OrderType;
    supplier?: Supplier;
    comment?: string;
    siteId?: number | null;
    sentToSupplier?: string;
    sentBy?: string;
    voucherNum?: number | null;
    cancelDate?: string;
    causeCancellation?: string;
    cancelBy?: string;
    paidToSupplier?: number | null;
    userName?: string;
    openDate?: string;
    finOrderType?: string;
    budgetItem?: number;
    confirmDate?: string;
    confirmBy?: string;
    confirmUserTz?: number | null;
    confirmByUser?: string;
    confirmCancelBy?: string;
    confirmCancelByUser?: string;
    confirmCancelDate?: string;
    confirmCancelUserTz?: number | null;
    supplierProcedureNum?: string;
}

