/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemsByTypeOrder } from './itemsByTypeOrder';


export interface OrderItemCommonDetails { 
    itemId?: number | null;
    itemIndex?: number;
    orderItemDetails?: ItemsByTypeOrder;
    amount?: number | null;
    itemCost?: number | null;
    billingSupplier?: number | null;
    billingCustomer?: number | null;
    peopleInTrip?: number | null;
    startDate?: string | null;
    endDate?: string | null;
    startHour?: string | null;
    endHour?: string | null;
}

