/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemsByTypeOrder } from './itemsByTypeOrder';
import { Status } from './status';
import { Supplier } from './supplier';


export interface OrderItem { 
    supplierOrder?: Supplier;
    statusOrder?: Status;
    tripId?: number;
    orderId?: number;
    itemIndx?: number;
    orderItemDetails?: ItemsByTypeOrder;
    itemId?: number | null;
    itemCost?: number | null;
    billingSupplier?: number | null;
    billingCustomer?: number | null;
    isVat?: number | null;
    start?: string | null;
    end?: string | null;
    amount?: number | null;
    startHour?: string | null;
    endHour?: string | null;
    exitPoint?: number | null;
    endPlace?: string | null;
    startPlace?: string | null;
    comment?: string | null;
    internalComment?: string | null;
    peopleInTrip?: number | null;
    userName?: string | null;
    generateDate?: string | null;
    approvedDate?: string | null;
    approvalTraining?: number | null;
    approvalTrainingUser?: string | null;
    approvalTrainingDate?: string | null;
    explainComment?: string | null;
    paymentApproval?: number | null;
    paymentApprovalUser?: string | null;
    paymentApprovalDate?: string | null;
    approvalAccountant?: number | null;
    approvalAccountantZikuyDate?: string | null;
    attributeManagerApproval?: number | null;
    attributeManagerApprovalDate?: string | null;
    guideTz?: number | null;
    guideType?: number | null;
    guideName?: string | null;
    rakazApproval?: number | null;
    rakazApprovalDate?: string | null;
    rakazApprovalUser?: string | null;
    guideId?: number | null;
}

