/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Supplier { 
    id?: number | null;
    name?: string | null;
    finId?: number | null;
    cityId?: number | null;
    address?: string | null;
    supplierType?: number | null;
    isValid?: number | null;
    phone?: string | null;
    email?: string | null;
    fax?: string | null;
    contact?: string | null;
    registrationNum?: string | null;
    supplierFinId?: number;
    isGuideSupplier?: number | null;
}

