/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Supplier { 
    id?: number;
    name?: string;
    finId?: number | null;
    cityId?: number | null;
    address?: string;
    supplierType?: number | null;
    isValid?: number | null;
    phone?: string;
    email?: string;
    fax?: string;
    contact?: string;
    registrationNum?: string;
    supplierFinId?: number;
    isGuideSupplier?: number | null;
<<<<<<< HEAD
    isXemptedFromVat?: boolean;
=======
    //isXemptedFromVat?: boolean;
    isXemptedFromVat?: number;
>>>>>>> 97f4ba4b533b0af77191e6b294ca025293b44238
}

