/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.12.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { BaseCustomer } from './baseCustomer';
import { AgeGroup } from './ageGroup';
import { LodgingReservation } from './lodgingReservation';
import { ActivityType } from './activityType';
import { KKLWorker } from './kKLWorker';
import { Area } from './area';
import { Language } from './language';
import { FieldForestCenter } from './fieldForestCenter';
import { TripAttribute } from './tripAttribute';
import { Country } from './country';
import { Budget } from './budget';
import { GroupGender } from './groupGender';


export interface TripInfo { 
    id?: number | null;
    tripDescription: string;
    tripStart: string;
    tripEnding: string;
    centerField: FieldForestCenter;
    activity: ActivityType;
    ageGroup: AgeGroup;
    attribute: TripAttribute;
    areaTrip?: Area;
    budget?: Budget;
    customer: BaseCustomer;
    groupGender?: GroupGender;
    kklWorker?: KKLWorker;
    customerPay?: BaseCustomer;
    commentManager?: string;
    contactName: string;
    contactPhone: string;
    contactEmail: string;
    confirm?: string;
    customerSignatureDate?: string | null;
    confirmBy?: string;
    country?: Country;
    /**
     * 1= Israel, 8= Abroad
     */
    departmentId: number;
    lodgingReservation?: Array<LodgingReservation>;
    /**
     * Trip creation date
     */
    generateTime?: string;
    language?: Language;
    numAccompanied?: number;
    numAdultAndYoung: number;
    numAccompaniedAndGuide?: number;
    numGuides?: number;
    numDrivers?: number;
    /**
     * number of kids less from two years old
     */
    numKids?: number;
    numShtilim?: number;
    noPayment?: number | null;
    tripStatus?: Status;
    userMobile?: string;
    userInfo?: string;
    reasonUnConfirm?: string;
    /**
     * 1=Inside center, 2=Outside center
     */
    insideCenterFieldId: number;
    addressCasualCustomer?: string;
    cityCasualCustomer?: string;
    zipCasualCustomer?: number | null;
    phoneCasualCustomer?: string;
    nameCasualCustomer?: string;
    isSalKKlGroup?: number | null;
    collectiveGroupId?: number | null;
    isOccupancyProblematic?: number | null;
}

