/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Area } from './area';
import { BaseCustomer } from './baseCustomer';
import { Language } from './language';
import { AgeGroup } from './ageGroup';
import { FieldForestCenter } from './fieldForestCenter';
import { LodgingReservation } from './lodgingReservation';
import { TripAttribute } from './tripAttribute';
import { ActivityType } from './activityType';
import { Country } from './country';
import { Budget } from './budget';


/**
 * describes the all trip details
 */
export interface TripInfo { 
    id?: number | null;
    tripDescription?: string | null;
    activity?: ActivityType;
    ageGroup?: AgeGroup;
    attribute?: TripAttribute;
    areaTrip?: Area;
    budget?: Budget;
    customer?: BaseCustomer;
    kklWorkerId?: number;
    kklWorkerName?: string;
    customerType?: string;
    customerRegionName?: string;
    customerPay?: BaseCustomer;
    customerPayType?: string;
    customerPayRegionName?: string;
    centerField?: FieldForestCenter;
    commentManager?: string | null;
    contactName?: string | null;
    contactPhone?: string | null;
    contactEmail?: string | null;
    confirm?: string | null;
    customerSignatureDate?: string | null;
    confirmBy?: string | null;
    country?: Country;
    /**
     * 1= Israel, 8= Abroad
     */
    departmentId?: number;
    lodgingReservation?: Array<LodgingReservation>;
    tripEnding?: string;
    /**
     * Trip creation date
     */
    generateTime?: string;
    language?: Language;
    numAccompanied?: number;
    numAdultAndYoung?: number;
    numAccompaniedAndGuide?: number;
    numGuides?: number;
    numDrivers?: number;
    numShtilim?: number;
    noPayment?: number | null;
    tripStart?: string;
    tripStatusId?: number;
    tripStatusName?: string;
    userMobile?: string | null;
    userId?: string | null;
    userName?: string | null;
    reasonUnConfirm?: string | null;
    /**
     * 1=Inside center, 2=Outside center
     */
    insideCenterFieldId?: number;
    addressCasualCustomer?: string | null;
    cityCasualCustomer?: string | null;
    zipCasualCustomer?: number | null;
    phoneCasualCustomer?: string | null;
    nameCasualCustomer?: string | null;
    isSalKKlGroup?: number | null;
    isOccupancyProblematic?: number | null;
}

