/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.12.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TripActivity { 
    /**
     * the unique activity Id
     */
    activityId?: number | null;
    subItemId?: number | null;
    activityName?: string;
    /**
     * refers to indentity record on trip activities table in data base
     */
    tripActivityIdentity?: number | null;
    date?: string;
    description?: string;
    fromHour?: string;
    tillHour?: string;
    tripId?: number;
}

