/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.11.1
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TripInfo } from './tripInfo';
import { Movements } from './movements';
import { OrderEvent } from './orderEvent';
import { TripActivity } from './tripActivity';


export interface TripModel { 
    trip?: TripInfo;
    activitiesList?: Array<TripActivity> | null;
    orderList?: Array<OrderEvent> | null;
    movementsList?: Array<Movements> | null;
}

