/**
 * kkl Education API
 * Education new project|
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: yochai@one1.co.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TripActivity { 
    /**
     * the unique activity Id
     */
    activityId?: number | null;
    activityName?: string;
    /**
     * refers to indentity record on trip activities table in data base
     */
    tripActivityIdentity?: number | null;
    categoryId?: number | null;
    date?: string;
    description?: string;
    hourStart?: string;
    hourEnd?: string;
    tripId?: number;
    userName?: string;
}

